package constanta

var (
	HeaderSalesReportSalesInvoice = []interface{}{
		"No. Invoice Sales",
		"No. Referensi",
		"Customer",
		"Tanggal",
		"Eksekutor",
		"Status",
		"Gudang",
		"Cabang",
		"Segmen Harga",
		"Jumlah Unit",
		"Subtotal",
		"Diskon (%)",
		"Diskon (Cashback)",
		"Total",
		"Nominal Retur",
		"Sisa Pembayaran",
		"Tgl. Pembayaran Terakhir",
		"Catatan Invoice",
		"Divisi",
	}

	HeaderSalesReportSalesInvoiceDetailAdmin = []interface{}{
		"No. Invoice Sales",
		"No. Ref",
		"Nama Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Pengiriman Dari",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun",
		"Spek",
		"Lengkap / Batang",
		"Grade SM",
		"Grade PGI",
		"Harga Dasar Saat Gadai",
		"Harga Dasar Grade A",
		"Adj. Grade",
		"Adj. Spec",
		"Adj. Batangan",
		"Adj. Lain-lain",
		"Adj. Pot / Tmbh",
		"Adj. Segmen Harga",
		"Diskon",
		"Total",
		"Modal",
		"Profit / Loss",
		"Catatan",
		"Catatan Lain-lain",
	}

	HeaderSalesReportSalesinvoiceDetailNonAdmin = []interface{}{
		"No. Invoice Sales",
		"No. Ref",
		"Nama Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Pengiriman Dari",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun",
		"Spek",
		"Lengkap / Batang",
		"Grade SM",
		"Grade PGI",
		"Adj. Pot / Tmbh",
		"Adj. Segmen Harga",
		"Diskon",
		"Total",
		"Catatan",
	}

	HeaderSalesReportInvoiceDetailAdjustment = []interface{}{
		"No. Invoice Sales",
		"No. Faktur Barang",
		"Nama Customer",
		"Nama Adjustment",
		"Nominal Adjustment",
	}

	HeaderSalesReportReturnInvoice = []interface{}{
		"No. Invoice Retur",
		"No. Invoice Sales",
		"Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"No. Ref",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun",
		"Spek",
		"Lengkap / Batangan",
		"Grade SM",
		"Grade PGI",
		"Refund",
		"Tanggal Retur",
		"Eksekutor",
		"Alasan Retur",
	}

	HeaderSalesReportInvoiceGold = []interface{}{
		"No. Invoice Sales",
		"No. Referensi",
		"Customer",
		"Tanggal",
		"Eksekutor",
		"Status",
		"Gudang",
		"Cabang",
		"Segmen Harga",
		"Jumlah Unit",
		"Subtotal",
		"Diskon Kadar",
		"Nominal Diskon",
		"Total",
		"Nominal Retur",
		"Sisa Pembayaran",
		"Tgl. Pembayaran Terakhir",
		"Catatan Invoice",
		"Divisi",
		"Jenis Invoice",
	}

	HeaderSalesReportInvoiceGoldDetail = []interface{}{
		"No. Invoice Sales",
		"No. Ref",
		"Nama Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Pengiriman Dari",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Kadar",
		"Berat Kotor",
		"Berat Potongan",
		"Berat Bersih",
		"Merk Cap Emas",
		"Tipe Emas",
		"Jumlah Keping",
		"Harga Dasar",
		"Diskon",
		"Total",
		"Modal",
		"Profit / Lost",
	}

	HeaderSalesReportInvoiceGoldDetailNonAdmin = []interface{}{
		"No. Invoice Sales",
		"No. Ref",
		"Nama Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Pengiriman Dari",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Kadar",
		"Berat Kotor",
		"Berat Potongan",
		"Berat Bersih",
		"Merk Cap Emas",
		"Tipe Emas",
		"Jumlah Keping",
		"Harga Dasar",
		"Diskon",
		"Total",
	}

	HeaderSalesReportReturnInvoiceGold = []interface{}{
		"No. Invoice Retur",
		"No. Invoice Sales",
		"Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"No. Ref",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Kadar",
		"Berat Kotor",
		"Berat Potongan",
		"Berat Bersih",
		"Merk Cap Emas",
		"Tipe Emas",
		"Jumlah Keping",
		"Refund",
		"Tanggal Retur",
		"Eksekutor",
		"Alasan Retur",
	}

	HeaderReturnInvoiceReport = []interface{}{
		"No. Invoice Retur",
		"No. Invoice Sales",
		"No. Ref Invoice Sales",
		"Customer",
		"Tanggal Retur",
		"Eksekutor",
		"Jumlah Item",
		"Nominal Pengembalian",
	}

	HeaderReturnInvoiceReportDetail = []interface{}{
		"No. Invoice Retur",
		"No. Invoice Sales",
		"Customer",
		"Tanggal Jual",
		"No. Faktur Barang",
		"No. Ref",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Gudang",
		"Cabang",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun",
		"Spek",
		"Lengkap / Batangan",
		"Grade SM",
		"Grade PGI",
		"Refund",
		"Tanggal Retur",
		"Eksekutor",
		"Alasan Retur",
	}

	HeaderCustomerTransactionReport = []interface{}{
		"Tanggal",
		"Customer",
		"Tipe Transaksi",
		"Nominal",
		"Perubahan Piutang",
		"Piutang Setelah",
		"Perubahan Hutang",
		"Hutang Setelah",
		"Eksekusi Oleh",
		"Catatan",
	}

	HeaderDeliveryBatchReport = []interface{}{
		"Kloter Pengiriman",
		"Cabang",
		"Pengiriman Dari",
		"Jumlah Item",
	}

	HeaderDeliveryItemEXTReport = []interface{}{
		"Kloter Pengiriman",
		"Cabang",
		"Pengiriman Dari",
		"No. Faktur",
		"IMEI / SN",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun / Generasi",
		"Tanggal Gadai",
		"Status",
		"Grade PGI",
		"Kelengkapan dari PGI",
		"Harga Dasar Saat Gadai",
		"Harga Dasar Sekarang",
		"Harga Jual",
		"Harga Modal",
		"Grade SM",
		"Spek",
		"Kelengkapan SM",
		"Gudang",
		"Aksesoris Tidak Ada",
		"Aksesoris Tidak Ori",
		"Approval Oleh",
		"Tanggal Approval",
		"Jam Approval",
		"Keterangan",
	}

	HeaderDeliveryItemReport = []interface{}{
		"Kloter Pengiriman",
		"Cabang",
		"Pengiriman Dari",
		"No. Faktur",
		"IMEI / SN",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun / Generasi",
		"Tanggal Gadai",
		"Status",
		"Grade PGI",
		"Kelengkapan dari PGI",
		"Harga Dasar Saat Gadai",
		"Harga Dasar Sekarang",
		"Harga Jual",
		"Grade SM",
		"Spek",
		"Kelengkapan SM",
		"Gudang",
		"Aksesoris Tidak Ada",
		"Aksesoris Tidak Ori",
		"Approval Oleh",
		"Tanggal Approval",
		"Jam Approval",
	}

	HeaderDeliveryItemGoldEXTReport = []interface{}{
		"Kloter Pengiriman",
		"Cabang",
		"Pengiriman Dari",
		"No. Faktur",
		"Jenis",
		"Merk",
		"Tipe",
		"Kadar",
		"Berat Kotor",
		"Berat Potongan",
		"Berat Bersih",
		"Merk Cap Emas",
		"Tipe Emas",
		"Jumlah Keping",
		"Status",
		"Harga Dasar",
		"Gudang",
		"Ada Cap",
		"Approval Oleh",
		"Tanggal Approval",
		"Jam Approval",
	}

	HeaderDeliveryItemGoldReport = []interface{}{
		"Kloter Pengiriman",
		"Cabang",
		"Pengiriman Dari",
		"No. Faktur",
		"Jenis",
		"Merk",
		"Tipe",
		"Kadar PGI",
		"Berat Kotor PGI",
		"Berat Potongan PGI",
		"Berat Bersih PGI",
		"Merk Cap Emas PGI",
		"Tipe Emas",
		"Jumlah Keping",
		"Tanggal Gadai",
		"Status",
		"Grade PGI",
		"Harga Dasar Saat Gadai",
		"Harga Dasar Sekarang",
		"Gudang",
		"Ada Cap",
		"Approval Oleh",
		"Tanggal Approval",
		"Jam Approval",
	}

	HeaderInventoryMovementReport = []interface{}{
		"No. Faktur",
		"No. Referensi",
		"Tanggal Perpindahan",
		"Tanggal Konfirmasi",
		"Eksekutor",
		"Status",
		"Gudang Asal",
		"Cabang Asal",
		"Gudang Tujuan",
		"Cabang Tujuan",
		"Jumlah Unit",
		"Catatan",
	}

	HeaderInventoryMovementItemReport = []interface{}{
		"No. Faktur",
		"No. Referensi",
		"No. Faktur Barang",
		"IMEI / SN",
		"Tanggal Gadai",
		"Kloter Pengiriman",
		"Gudang Asal",
		"Cabang Asal",
		"Gudang Tujuan",
		"Cabang Tujuan",
		"Jenis",
		"Merk",
		"Tipe",
		"Tahun",
		"Spek",
		"Lengkap / Batang",
		"Grade SM",
		"Grade PGI",
		"Harga Dasar Saat Gadai",
		"Modal",
	}

	HeaderCatalogCustomerLoginReport = []interface{}{
		"Nama Customer",
		"Nama Toko",
		"E-Mail",
		"No. Handphone",
		"Alamat",
		"Tanggal Login",
		"Jam Login",
	}

	HeaderUserTaskCountLogsReport = []interface{}{
		"Tanggal",
		"Nama",
		"Jumlah Approve Barang",
		"Jumlah Input Invoice",
		"Jumlah Retur Barang",
		"Jumlah Reset Inventory",
		"Jumlah Update Kerusakan",
		"Jumlah Cetak Barcode",
		"Jumlah Pindah Gudang",
		"Jumlah Upload Foto Video",
		"Jumlah Input Aksesoris",
	}

	HeaderInventoryReturnReport = []interface{}{
		"No. Faktur",
		"Status",
		"Tanggal Request",
		"Jam Request",
		"Note Request",
		"Tanggal Diproses",
		"Jam Diproses",
		"Diproses Oleh",
		"Tanggal Pembatalan",
		"Note Pembatalan",
		"Dibatalkan Oleh",
	}

	HeaderSendbackReport = []interface{}{
		"No. Faktur",
		"Tanggal Pengiriman",
		"Tanggal Konfirmasi",
		"Eksekutor",
		"Status",
		"Gudang Asal",
		"Jumlah Unit",
		"Catatan",
	}

	HeaderSendbackDetailReport = []interface{}{
		"No. Faktur",
		"No. Faktur Barang",
		"Kloter Pengiriman",
		"Jenis Barang",
		"IMEI / SN",
		"Merk",
		"Tipe Barang",
		"Spec",
		"Tahun",
		"Lengkap / Batang",
		"Grade SM",
		"Grade PGI",
		"Harga",
		"Nama Gudang",
		"Tipe Kerusakan",
	}
)
